"""init.

Revision ID: 0ac409a761fe
Revises:
Create Date: 2025-03-28 16:13:39.590887

"""

import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision = "0ac409a761fe"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transports",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("speed", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "couriers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("transport_id", sa.UUID(), nullable=True),
        sa.Column("coord_x", sa.SmallInteger(), nullable=False),
        sa.Column("coord_y", sa.SmallInteger(), nullable=False),
        sa.Column("status", sa.Enum("Free", "Busy", name="courier_status"), nullable=False),
        sa.ForeignKeyConstraint(
            ["transport_id"],
            ["transports.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("coord_x", sa.SmallInteger(), nullable=False),
        sa.Column("coord_y", sa.SmallInteger(), nullable=False),
        sa.Column("status", sa.Enum("Created", "Assigned", "Completed", name="order_status"), nullable=False),
        sa.Column("courier_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["courier_id"],
            ["couriers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("orders")
    op.drop_table("couriers")
    op.drop_table("transports")
    # ### end Alembic commands ###
